pool:
  name: 'Genexus'  # Reemplaza con el nombre de tu pool

jobs:
- job: UpdateGXServer
  displayName: 'Update GX Server'
  steps:
  - powershell: "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\lhuens\Desktop\msbuild.msbuild" /t:Update /p:KBPath="C:\Models\GX18U9\SelectorCastrol"
    displayName: 'Ejecutar MSBuild'


