pool:
  name: 'Genexus'  # Reemplaza con el nombre de tu pool

jobs:
- job: UpdateGXServer
  displayName: 'Update GX Server'
  steps:
  - poweshell: |
      echo "Ejecutando script en el pool de agentes."
      # Aquí van tus comandos
    displayName: 'Ejecutar comandos'
